sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # https://sdk.cloud.google.com - install gcp sdk and everything after that is to install locally on our instance by travis ci
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # $Home/google-cloud-sdk - look at dir of google cloud sdk and apply some config inside shell in travis
  - source $Home/google-cloud-sdk/path.bash.inc
  # install kubectl inside travis env
  - gcloud components update kubectl
  #authenticate with GCP
  - gcloud auth activate-service-account --key-file service-account.json