sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # https://sdk.cloud.google.com - install gcp sdk and everything after that is to install locally on our instance by travis ci
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  # $Home/google-cloud-sdk - look at dir of google cloud sdk and apply some config inside shell in travis
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install kubectl inside travis env
  - gcloud components update kubectl
  #authenticate with GCP
  - gcloud auth activate-service-account --key-file service-account.json
  #set below three commands on shell in GCP terminal to configure kubectl in console in GCP
  - gcloud config set project multi-k8s-394918
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t pkhot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pkhot/react-test npm test

# tell travis to use the oustide script file deploy.sh for deployment
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main

